sudo: false
group: travis_latest
language: python
cache: pip
matrix:
  fast_finish: true
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
      dist: xenial
      sudo: true
    - python: "nightly"
  allow_failures:
    - python: "nightly"
before_install:
  - pip install poetry
install:
  - poetry install -vvv
script:
  - python -m pytest
