dist: bionic
os: linux
group: travis_latest
language: python
cache: pip
jobs:
  fast_finish: true
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "nightly"
  allow_failures:
    - python: "nightly"
before_install:
  - pip install poetry
install:
  - poetry install -vvv
script:
  - poetry run pytest
