[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
]

[tool.coverage.run]
omit = [
    "*/setup.py",
    "*/tests/*",
    "*/build/*",
    "*/dist/*",
    "*/.tox/*",
    "*/.egg/*",
]

[tool.isort]
force_sort_within_sections = false
known_first_party = "bugmon"
profile = "black"

[tool.poetry]
name = "bugmon"
readme = "README.md"
description = "A python module for analyzing SpiderMonkey and Firefox bugs"
version = "0.8.6"
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Testing",
    "Topic :: Security",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
]
keywords = ["fuzz", "fuzzing", "security", "test", "testing", "bisection"]
authors = [
    "Christian Holler <choller@mozilla.com>",
    "Jason Kratzer <jkratzer@mozilla.com>"
]
maintainers = [
    "Mozilla Fuzzing Team <fuzzing@mozilla.com>"
]
license = "MPL-2.0"
repository = "https://github.com/MozillaSecurity/bugmon"
homepage = "https://github.com/MozillaSecurity/bugmon"

[tool.poetry.dependencies]
python = "^3.6.1"
toml = "^0.9"
fuzzfetch = "^1.3.0"
bugsy = {git = "https://github.com/AutomatedTester/Bugsy.git"}
black = "^19.10b0"
autobisect = "^0.14.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
flake8-isort = "^4.0.0"
flake8-quotes = "^2.1.1"
pytest = "^6.2.3"
pytest-flake8 = "^1.0.7"
pytest-black = "^0.3.12"
pre-commit = "^2.1.1"
tox = "^3.14.5"
pylint = "^2.4.4"
pytest-pylint = "^0.18.0"
pytest-mock = "^3.6.0"
codecov = "^2.1.11"
pytest-cov = "^2.11.1"
toml-sort = "^0.19.0"
gitlint = "^0.15.1"

[tool.poetry.scripts]
bugmon = "bugmon.main:main"

[tool.pylint.format]
max-line-length = 88

[tool.pylint.messages_control]
disable = [
    "bad-continuation",
    "fixme",
    "invalid-name",
    "line-too-long",
    "logging-format-interpolation",
    "logging-fstring-interpolation",
    "missing-module-docstring",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-branches",
    "too-many-instance-attributes",
    "too-many-lines",
    "too-many-locals",
    "too-many-nested-blocks",
    "too-many-return-statements",
    "too-many-statements",
    "useless-object-inheritance"
]

[tool.pytest.ini_options]
log_level = "DEBUG"
