[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "bugmon"
description = "A python module for analyzing SpiderMonkey and Firefox bugs"
version = "0.7.0"

classifiers=[
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Testing",
    "Topic :: Security",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
]
keywords = ["fuzz", "fuzzing", "security", "test", "testing", "bisection"]

authors = [
    "Christian Holler <choller@mozilla.com>",
    "Jason Kratzer <jkratzer@mozilla.com>"
]
maintainers = [
    "Mozilla Fuzzing Team <fuzzing@mozilla.com>"
]

license = "MPL-2.0"
# readme = "README.md"

repository = "https://github.com/MozillaSecurity/autobisect"
homepage = "https://github.com/MozillaSecurity/autobisect"


[tool.poetry.dependencies]
python = "^3.6"
toml = "^0.9"
ffpuppet = "^0.7.0"
fuzzfetch = "^0.9.9"
bugsy = {git = "https://github.com/AutomatedTester/Bugsy.git"}
black = "^19.10b0"
autobisect = "^0.7.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
flake8-isort = "^2.8.0"
flake8-quotes = "^2.1.1"
pytest = "^5.3.5"
pytest-flake8 = "^1.0.4"
pytest-black = "^0.3.8"
pre-commit = "^2.1.1"
tox = "^3.14.5"
pylint = "^2.4.4"
pytest-pylint = "^0.15.1"

[tool.poetry.scripts]
bugmon = "bugmon.main:main"

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
  | build
  | dist
)/
'''
