name: Setup Poetry
description: Cross-platform Poetry installation

runs:
  using: "composite"
  steps:
    - name: Install Poetry (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Poetry (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
        echo "$env:APPDATA\Python\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Append

